config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create', as: :create_task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update', as: :update_task
  delete 'tasks/:id', to: 'tasks#delete', as: :delete_task
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(title: params[:task][:title], details: params[:task][:details])
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(title: params[:task][:title], details: params[:task][:details], completed: params[:task][:completed])
    @task.save
    redirect_to update_task_path(@task)
  end

  def delete
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container mt-3">
  <div class="adjust-width">
    <%= form_for @task do |task| %>
      <div class="form-group">
        <%= task.label :title %>
        <%= task.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= task.label :details %>
        <%= task.text_field :details, class: "form-control" %>
      </div>
      <div class="form-check">
        <%= task.check_box :completed, class: "form-check-input", type: "checkbox" %>
        Completed
      </div>
      <div class="d-flex">
        <%= task.submit "Edit task", class: "btn btn-secondary flex-grow-1 mt-3" %>
    </div>
    <% end %>
    <br>
    <%= link_to "Back to all tasks", tasks_path %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="banner">
  <div class="container mt-3">
    <div class="adjust-width">
      <div class="row justify-content-left mb-3">
        <h1>
          My tasks
        </h1>
      </div>
      <% @tasks.each do |task| %>
        <div class="row justify-content-left">
            <% if task.completed == true then %>
                <i class="far fa-check-circle mr-2"></i>
              <% end %>
              <% if task.completed == false then %>
                <i class="far fa-circle mr-2"></i>
              <% end %>
            <div class="flex-grow-1">
              <%= link_to task.title, task_path(task) %>
            </div>
            <%= link_to delete_task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="ml-2 fas fa-trash-alt"></i>
            <% end %>
        </div>
      <% end %>
      <div class="row justify-content-left mt-3">
        <%= link_to "Add new task", new_task_path %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container mt-3">
  <div class="adjust-width">
    <%= form_for @task do |task| %>
      <div class="form-group">
        <%= task.label :title %>
        <%= task.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= task.label :details %>
        <%= task.text_field :details, class: 'form-control' %>
      </div>
      <div class="d-flex">
        <%= task.submit "Create task", class: 'btn btn-primary flex-grow-1 mt-3' %>
      </div>
    <% end %>
    <br>
    <%= link_to "Back to tasks", tasks_path %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="adjust-width">
    <h1 class="challenge-headline"><%= @task.title %></h1>
    <p><%= @task.details %></p>
    <div class="mb-4">
      <% if @task.completed == true then %>
        <i class="far fa-check-circle mr-2"></i> completed
      <% end %>
      <% if @task.completed == false then %>
        <i class="far fa-circle mr-2"></i> pending
      <% end %>
    </div>
    <div class="d-flex">
      <%= link_to "Edit", edit_task_path, class: "btn btn-primary flex-grow-1 mr-1" %>
      <%= link_to "Back", tasks_path, class: "btn btn-primary flex-grow-1 mr-1" %>
      <%= link_to "Delete", delete_task_path(@task),  method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary flex-grow-1" %>
    </div>
  </div>
</div>